"""Train the diamond price models and create deployment artifacts."""

from pathlib import Path
import json

import joblib
import matplotlib.pyplot as plt
import pandas as pd
from docx import Document
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import Lasso, LinearRegression, Ridge
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeRegressor

from src.diamond_price_prediction.evaluation import evaluate_regression_model
from src.diamond_price_prediction.preprocessing import preprocess_data


ROOT = Path(__file__).resolve().parent
DATA_PATH = ROOT / "data" / "diamonds.csv"
MODEL_DIR = ROOT / "model"
OUTPUT_DIR = ROOT / "outputs"
FIGURES_DIR = OUTPUT_DIR / "figures"
METRICS_DIR = OUTPUT_DIR / "metrics"
PREDICTIONS_DIR = OUTPUT_DIR / "predictions"
REPORT_DIR = ROOT / "report"


def create_output_directories():
    for directory in (MODEL_DIR, FIGURES_DIR, METRICS_DIR, PREDICTIONS_DIR, REPORT_DIR):
        directory.mkdir(parents=True, exist_ok=True)


def save_report(metrics, best_name, best_params, row_count):
    document = Document()
    document.add_heading("Diamond Price Prediction Project Report", level=0)
    document.add_paragraph("Educational machine learning report generated by train_model.py.")
    document.add_heading("Dataset", level=1)
    document.add_paragraph(f"Processed records: {row_count:,}. Target: diamond price in US dollars.")
    document.add_heading("Model comparison", level=1)
    table = document.add_table(rows=1, cols=5)
    for cell, heading in zip(table.rows[0].cells, ["Model", "R2", "RMSE", "MAE", "MAPE"]):
        cell.text = heading
    for result in metrics:
        cells = table.add_row().cells
        cells[0].text = result["Model"]
        cells[1].text = f"{result['R2']:.4f}"
        cells[2].text = f"${result['RMSE']:,.0f}"
        cells[3].text = f"${result['MAE']:,.0f}"
        cells[4].text = f"{result['MAPE']:.4f}"
    document.add_heading("Selected model", level=1)
    document.add_paragraph(f"{best_name}. Parameters: {best_params}")
    document.add_paragraph("This model is not a certified appraisal tool and should not be used as a guaranteed market valuation.")
    document.save(REPORT_DIR / "Diamond_Price_Project_Report.docx")


def train_and_save_models():
    create_output_directories()
    data = preprocess_data(pd.read_csv(DATA_PATH))
    X = data.drop(columns=["price"])
    y = data["price"]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    models = {
        "Linear Regression": Pipeline([("scale", StandardScaler()), ("model", LinearRegression())]),
        "Ridge": Pipeline([("scale", StandardScaler()), ("model", Ridge(alpha=1.0))]),
        "Lasso": Pipeline([("scale", StandardScaler()), ("model", Lasso(alpha=10.0, max_iter=10000))]),
        "Decision Tree": DecisionTreeRegressor(max_depth=12, random_state=42),
        "Random Forest": RandomForestRegressor(n_estimators=150, random_state=42, n_jobs=-1),
        "Gradient Boosting": GradientBoostingRegressor(n_estimators=200, max_depth=5, random_state=42),
        "KNN (K=11)": Pipeline([("scale", StandardScaler()), ("model", KNeighborsRegressor(n_neighbors=11, n_jobs=-1))]),
    }

    results = []
    predictions = {}
    for name, model in models.items():
        model.fit(X_train, y_train)
        prediction = model.predict(X_test)
        results.append(evaluate_regression_model(name, y_test, prediction))

    tuned_model = RandomForestRegressor(
        n_estimators=200, max_depth=15, min_samples_leaf=1, random_state=42, n_jobs=-1
    )
    tuned_model.fit(X_train, y_train)
    tuned_prediction = tuned_model.predict(X_test)
    tuned_result = evaluate_regression_model("Random Forest (Tuned)", y_test, tuned_prediction)
    results.append(tuned_result)

    metrics = pd.DataFrame(results).sort_values("R2", ascending=False).reset_index(drop=True)
    metrics.to_csv(METRICS_DIR / "model_comparison.csv", index=False)
    pd.DataFrame({"actual_price": y_test, "predicted_price": tuned_prediction}).to_csv(
        PREDICTIONS_DIR / "test_predictions.csv", index=False
    )

    importance = pd.DataFrame({"feature": X.columns, "importance": tuned_model.feature_importances_})
    importance.sort_values("importance", ascending=False).to_csv(METRICS_DIR / "feature_importance.csv", index=False)

    plt.figure(figsize=(8, 6))
    plt.scatter(y_test, tuned_prediction, alpha=0.25, s=8, color="teal")
    bounds = [min(y_test.min(), tuned_prediction.min()), max(y_test.max(), tuned_prediction.max())]
    plt.plot(bounds, bounds, "k--", linewidth=1)
    plt.xlabel("Actual price ($)")
    plt.ylabel("Predicted price ($)")
    plt.title("Tuned Random Forest: Actual vs Predicted")
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "actual_vs_predicted.png", dpi=150)
    plt.close()

    plt.figure(figsize=(8, 6))
    top_features = importance.sort_values("importance").tail(10)
    plt.barh(top_features["feature"], top_features["importance"], color="teal")
    plt.xlabel("Importance")
    plt.title("Top Feature Importance")
    plt.tight_layout()
    plt.savefig(FIGURES_DIR / "feature_importance.png", dpi=150)
    plt.close()

    joblib.dump(tuned_model, MODEL_DIR / "diamond_price_pipeline.pkl")
    metadata = {
        "model_name": "Random Forest (Tuned)",
        "target": "price",
        "features": list(X.columns),
        "categorical_orders": {
            "cut": ["Fair", "Good", "Very Good", "Premium", "Ideal"],
            "color": ["J", "I", "H", "G", "F", "E", "D"],
            "clarity": ["I1", "SI2", "SI1", "VS2", "VS1", "VVS2", "VVS1", "IF"],
        },
        "metrics": tuned_result,
    }
    (MODEL_DIR / "model_meta.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    save_report(results, "Random Forest (Tuned)", tuned_model.get_params(), len(data))

    print(metrics.to_string(index=False))
    print(f"\nSaved model and artifacts under {ROOT}")


if __name__ == "__main__":
    train_and_save_models()